name: CI
run-name: ${{ github.actor }} is deploying 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm install -g turbo
      # - run: turbo run lint --filter=proyecto1
      # - run: turbo run test --filter=proyecto2
      - run: npm run build